services:
  boxxed:
    build: .
    container_name: boxxed
    ports:
      - "3001:3001"
    volumes:
      - ./data:/app/data
    environment:
      PORT: 3001
      SESSION_SECRET: "flhkads65lkhñasdjhfoih45"
      SESSION_SECURE: "false"
    restart: unless-stopped